limit_req_zone $binary_remote_addr zone=thread_limit:10m rate=90r/m;

server {
    server_name ashstackapi.cloud;

    location /threads {
        limit_req zone=thread_limit;
        proxy_pass http://localhost:5000;
    }

    location / {
        proxy_pass http://localhost:5000;
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/ashstackapi.cloud/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/ashstackapi.cloud/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}

server {
    if ($host = ashstackapi.cloud) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    server_name ashstackapi.cloud;
    return 404; # managed by Certbot


}